### ISSUE TITLE
Section video background not passing html validation

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson-Shortcodes-Extension#13]
Fix 

change 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/views/view.php#L16

to 

    $bg_video_data_attr     = "data-wallpaper-options='".json_encode(array('source' => array('video' => $atts['video'])))."'";

**Comment by moldcraft** [comment]
Thank you

**Comment by danyj** [comment]
Thank you for double quotes :)
