### ISSUE TITLE
Custom styles in wp-editor

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson-Shortcodes-Extension#15]
Hi,

I am trying to add custom style to the toolbar, as described here : http://codex.wordpress.org/TinyMCE_Custom_Styles

But it does not work for the text-block shortcode editor (Although it's working on the regular WP editor)
I tried adding the code the text-block shortcode options.php : 

```
$options = array(
	'text' => array(
		'type'   => 'wp-editor',
		'teeny'  => false,
		'reinit' => true,
    	        'tinymce' => true,
		'label'  => __( 'Content', 'fw' ),
		'desc'   => __( 'Enter some content for this texblock', 'fw' ),
		'style_formats' => json_encode( array(  
											array(  
												'title' => 'My custom title',  
												'block' => 'h3',  
												'classes' => 'custom-title',
												'wrapper' => true,
												
											),  
										) )
	)
);
```
But it does not work.
I also cannot get the editor to init with the visual editor by default, it's always the "Text" editor that is shown be default.

I find it strange that the editors within the page builder aren't affected by the filters that affect the regular WP editor, what do you think ?

**Comment by ierpe** [comment]
great I will try this and let you know if anything goes wrong! Thanks

**Comment by ierpe** [comment]
Hi,

I am currently trying again to add custom style to the toolbar of the wp-editor, but I still cannot get it to work...
Could you provide me with a code exemple or the documentation if it exists on how to achieve this?

**Comment by moldcraft** [comment]
Sorry, currently no one in our team is familiar with wp-editor option-type. The developer that made it is no longer in our team. We will inspect this, but later.

**Comment by moldcraft** [comment]
Option-type wp-editor was [fixed](https://github.com/ThemeFuse/Unyson/compare/87675985308a15da80e3167638a388647da50539...59c0d00f8c75f0b99c3b83cd31f63b06374a77a5?diff=split&name=59c0d00f8c75f0b99c3b83cd31f63b06374a77a5), it should work now. Please [download Unyson latest dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip) and test.

I tested [this code](http://codex.wordpress.org/TinyMCE_Custom_Styles#Using_style_formats) and [it works](https://static.md/667c74c7e3f5710feafcbaafac447042.png).
