### ISSUE TITLE
We plan to extend shortcodes like tabs, accordions in order to be possible to add different shortcodes in each tab.

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Shortcodes-Extension#16]
We plan to extend shortcodes like tabs, accordions in order to be possible to add different shortcodes in each tab.

**Comment by andreiglingeanu** [comment]
Isn't this solved by [WP-Shortcodes](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension)?

**Comment by danyj** [comment]
@andreiglingeanu   should be if we get the editor button working ,

**Comment by andreiglingeanu** [comment]
@danyj We do.
