### ISSUE TITLE
[Question] Duplicating "Section" shortcode ?

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-Shortcodes-Extension#22]
Hello,

I'm having trouble to create a new item wrapper like "section shortcode" for the page builder. So my question is : is that only possible ? 
Because I duplicated it, renamed everything and as a result : no error but that doesn't works. 
As I know it's quite a special shortcode so I'm just wondering.

Thanks,

2F

**Comment by 2Fwebd** [comment]
So it's not possible ? If so, no problem I'll find another way :)
2F

**Comment by moldcraft** [comment]
It should be possible. I can't say for sure because I didn't made it.

**Comment by martinburdon** [comment]
Hi,

I can confirm I've duplicated the section shortcode into a plugin which I'm using in a theme that's in development and it's working fine.

**Comment by dmbostan** [comment]
@martinburdon can you offer an example how you did it?

**Comment by martinburdon** [comment]
@dmbostan sure thing

I have my shortcodes extracted out into a plugin as they're plugin territory, in my plugin I have the following folder structure for shortcodes which you need to follow for Unyson.

`extensions/shortcodes/shortcodes`

Then in that folder I have my shortcodes, for the section shortcode I simply took the section shortcode folder from the Unyson plugin and added it, then modified it to suit my needs. You can find it in the Unyson plugin at the following path:

`unyson/framework/extensions/shortcodes/shortcodes/section`.

Here is a screenshot of my plugin folder structure for clarity:

![screen shot 2016-09-27 at 20 06 31](https://cloud.githubusercontent.com/assets/4599099/18887867/edb4b6ce-84ed-11e6-9380-a76c12a6f537.png)

Hope that helps

**Comment by dmbostan** [comment]
@martinburdon do you have the Save template option in your custom section? It seems to be missing for duplicated sections. The default, however, is ok.

**Comment by martinburdon** [comment]
Hey @dmbostan,

It looks like it's not there for me - I'm assuming this feature was added after I had duplicated the section shortcode and overridden it. I guess it could be added in by duplicating the latest version of the section shortcode as in my comment above then adding your overwrites in again.

Hope that helps

**Comment by andreiglingeanu** [comment]
I'm not sure, but I remember the templates for sections being hardcoded for the original section shortcode only. I can be wrong, though.
