### ISSUE TITLE
Issue with image (Media element)

### ISSUE THREAD

**Issue by thanhluu** [ThemeFuse/Unyson-Shortcodes-Extension#23]
When I input specific width and height, the front-end only show attachment ID of image. Can you check the view of this element on page builder.

**Comment by moldcraft** [comment]
Details?

**Comment by thanhluu** [comment]
Updated

**Comment by moldcraft** [comment]
[The view](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/media-image/views/view.php) looks ok. On my side it works fine.

**Comment by thanhluu** [comment]
On my side, the image markup is showing like this:

![image](https://cloud.githubusercontent.com/assets/66447/8392177/31d14abc-1d0b-11e5-88d4-67b4967a13e6.png)

**Comment by moldcraft** [comment]
You use the default view, or you customized it in

```
{theme}/framework-customizations/extensions/shortcodes/media-image/views/view.php
```

?

**Comment by thanhluu** [comment]
On the default view only. I didn't customize that view.

**Comment by moldcraft** [comment]
I don't know how to reproduce the problem.

Can you debug the view (add some `fw_print()`)

```
plugins/unyson/framework/extensions/shortcodes/media-image/views/view.php
```

and detect the problem?

Or send me the access details to your site (with possibility to edit files - ftp access) to `moldcraft[at]email.com`? and I will debug it myself

**Comment by thanhluu** [comment]
Sorry this project still on my localhost.
I think the problem is `fw_resize` function return only the attachment's ID.

**Comment by moldcraft** [comment]
A temporary solution

```php
if (is_numeric($image)) {
    $image = $atts['image']['url'];
}
```

This is all I can help right now. I am not familiar with the `fw_resize()` functionality.

@valeriuzdrobau Will inspect this problem (most likely on Monday).

**Comment by thanhluu** [comment]
Ok! Thanks for your fast reply.

**Comment by valeriuzdrobau** [comment]
Hi, please check if you have an attachment with `412` ID.

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.
