### ISSUE TITLE
Button shortcode error: No decoder found

### ISSUE THREAD

**Issue by albertso** [ThemeFuse/Unyson-Shortcodes-Extension#26]
I'm getting _"Shortcode attributes decode error: No decoder found"_ in frontend when rendering buttons on a pricing table.

http://prntscr.com/7trnsr
http://prntscr.com/7troei

These buttons are rendered in line 54 in https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/table/views/pricing.php

    <?php echo $button->render($atts['table']['content'][ $row_key ][ $col_key ]['button']); ?>

The content of my page:

[table table="{"rows":[{"name":"default-row"},{"name":"pricing-row"},{"name":"button-row"}],"cols":[{"name":"default-col"},{"name":"default-col"}],"header_options":{"table_purpose":"pricing"},"content":[[{"textarea":"\\t\\tColumn 1\\t\\t"},{"textarea":"\\t\\tColumn 2\\t\\t"}],[{"amount":"100","description":""},{"amount":"200","description":""}],[{"button":{"label":"Contact","link":"#","target":"_self","color":""}},{"button":{"label":"Contact","link":"#","target":"_self","color":""}}]]}" _array_keys="{"table":"table"}" _made_with_builder="true"][/table]

... the atts are stored in json:

    {
        "button": {
            "label": "Contact",
            "link": "#",
            "target": "_self",
            "color": ""
        }
    }

if I do a button shortcode alone, it works fine, the attributes are stored in shortcode format:

    [button label="Submit" link="#" target="_self" color="" _made_with_builder="true"][/button]

I don't know what's wrong, but looks like it has to do with the latest commit: 3c8461e70192a0ff9d391f411a81a70353eaee59

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/730


We will create a release with the fix tomorrow.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/105
