### ISSUE TITLE
Add the ability to use a different map theme

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson-Shortcodes-Extension#28]
It would be good to be able to paste in a new map theme from somewhere such as https://snazzymaps.com

**Comment by martinburdon** [comment]
Pull request: https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/27

**Comment by moldcraft** [comment]
That feature will be removed because of snazzymaps license.

https://github.com/ThemeFuse/Unyson/issues/826
