### ISSUE TITLE
Can't save checkbox value for a section from page builder

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Shortcodes-Extension#31]
When you have a section inserted into page builder, you have an "Edit" button to open modal with settings. I've overwrited this [file](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/options.php) in our theme, in order to add some other options. I've found out that checkboxes are somehow broken in this modal. Their value is not sent correctly to the server. They work perfectly fine in "Theme Settings".

This problem exist just for options with type "checkbox"

Can you please give some more advice in order to investigate and solve this problem?

Thank you.

**Comment by danyj** [comment]
@andreiglingeanu  what is your checkbox array?

**Comment by andreiglingeanu** [comment]
@danyj Here's my `$options` array.
```
$options = array(
	'is_fullwidth' => array(
		'label'        => __('Full Width', 'fw'),
		'type'         => 'switch',
	),

	'is_cool' => array(
		'type'  => 'checkbox',
		'value' => true,
		'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
		'label' => __('Label', 'fw'),
		'desc'  => __('Description', 'fw'),
		'help'  => __('Help tip', 'fw'),
		'text'  => __('Yes', 'fw'),
	),

	'have_gutters' => array(
		'label'        => __('Have Gutters', 'fw'),
		'type'         => 'switch',
		'value'        => true
	),

	'background_color' => array(
		'label' => __('Background Color', 'fw'),
		'desc'  => __('Please select the background color', 'fw'),
		'type'  => 'color-picker',
	),
	'background_image' => array(
		'label'   => __('Background Image', 'fw'),
		'desc'    => __('Please select the background image', 'fw'),
		'type'    => 'background-image',
		'choices' => array(//	in future may will set predefined images
		)
	),
	'video' => array(
		'label' => __('Background Video', 'fw'),
		'desc'  => __('Insert Video URL to embed this video', 'fw'),
		'type'  => 'text',
	)
);

```

**Comment by danyj** [comment]
Try this one see if it works 


	'testswitch' => array(
		'label' => __('Label', 'fw'),
		'desc' => __('Desc', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'hide',
			'label' => __('Hide', 'fw')
		),
		'left-choice' => array(
			'value' => 'show',
			'label' => __('Show', 'fw')
		),
		'value' => 'show'
	)

I think there might still be an issue with true or false

https://github.com/ThemeFuse/Unyson/issues/642
https://github.com/ThemeFuse/Unyson/issues/670

**Comment by andreiglingeanu** [comment]
@danyj `'type' => 'switch' works great. The problem is present just on checkboxes. Yep, there's definitely a problem with those boolean values. I'll stick with switches for now.

**Comment by danyj** [comment]
ok , see this , 
https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111552098

try to build it that way 

aka:


                'test-checkboxes' => array(
                    'type' => 'checkboxes',
                    'choices' => array(
                        'text' => 'Text',
                        1 => '1',
                        0 => '0',
                    ),
                ),

**Comment by danyj** [comment]
no wait , those tested are   
switch 
radio
checkboxes ( emphasis on 's) 

seems like checkboX  was not looked at  and it should   work as in docs 
http://manual.unyson.io/en/latest/options/built-in-option-types.html#checkbox

@moldcraft  might give it a look

**Comment by andreiglingeanu** [comment]
Yep, checkbox groups are indeed working, which is not the case with single checkbox. Thank you.

**Comment by moldcraft** [comment]
@andreiglingeanu Test please if it works fine now.

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/121

**Comment by danyj** [comment]
@moldcraft  on it

**Comment by danyj** [comment]
Added this in section options 


		'section_testcheck' => array(
			'type'  => 'checkbox',
			'value' => true, // checked/unchecked
			'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
			'label' => __('Label', 'fw'),
			'desc'  => __('Description', 'fw'),
			'help'  => __('Help tip', 'fw'),
			'text'  => __('Yes', 'fw'),
		),


before this fix 
http://prntscr.com/8c3o0o

after the fix 

http://prntscr.com/8c3o7y

also tested switch 


		'section_switch' =>array (
				
				'type'  => 'switch',
				'value' => true,
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label', 'fw'),
				'desc'  => __('Description', 'fw'),
				'help'  => __('Help tip', 'fw'),
				'left-choice' => array(
					'value' => false,
					'label' => __('False', 'fw'),
				),
				'right-choice' => array(
					'value' => true,
					'label' => __('True', 'fw'),
				),
				
		
		),


both work fine visually in backend ,  but 

the front output is wrong, set both of those to FALSE , and save , reload admin they will stay at false 

add this in section view.php


	if(fw_akg('section_testcheck',$atts)){
		fw_print($atts);
	}


this is what I get 

http://prntscr.com/8c3s6a

they both stay at 1   in stead 0

**Comment by danyj** [comment]
same thing with 0 and 1 


		'section_testcheck' => array(
			'type'  => 'checkbox',
			'value' => 0, // checked/unchecked
			'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
			'label' => __('Label', 'fw'),
			'desc'  => __('Description', 'fw'),
			'help'  => __('Help tip', 'fw'),
			'text'  => __('Yes', 'fw'),
		),
		
		'section_switch' =>array (
				
				'type'  => 'switch',
				'value' => 0,
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label', 'fw'),
				'desc'  => __('Description', 'fw'),
				'help'  => __('Help tip', 'fw'),
				'left-choice' => array(
					'value' => 0,
					'label' => __('False', 'fw'),
				),
				'right-choice' => array(
					'value' => 1,
					'label' => __('True', 'fw'),
				),
				
		
		),

**Comment by danyj** [comment]
@moldcraft  disregard  please, 

I mistakenly added 2 sections  and was getting print from other one 


fix works
