### ISSUE TITLE
Use image `alt` from attachment

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson-Shortcodes-Extension#32]
[Here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/239568aabb7178d3dc4bfda094204edbc5cd0e30/shortcodes/media-image/views/view.php#L26) should be [this](https://static.md/971433b2c556307a8f14093ea2627f79.png).

**Comment by anjanphukan** [comment]
Is it fixed?

**Comment by moldcraft** [comment]
[Yes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/ec003e1334d2436a3712d7b202003872aaedadae/shortcodes/media-image/views/view.php#L22), but the release will be later.
