### ISSUE TITLE
Disable default styles

### ISSUE THREAD

**Issue by alvisir** [ThemeFuse/Unyson-Shortcodes-Extension#33]
Hi, 
what is the right way to disable the default elements stylesheets? I'd like to use my styles.
I tried to disable them using  `wp_dequeue_style` function but does not work.

**Comment by moldcraft** [comment]
Shortcode styles are enqueued from [`static.php`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/button/static.php), you can create 
`static.php` in theme and it will overwrite the one in framework

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/{SHORTCODE_NAME}/static.php
```
