### ISSUE TITLE
Add options to row shortcode

### ISSUE THREAD

**Issue by tzimpel** [ThemeFuse/Unyson-Shortcodes-Extension#35]
Hi,

I'm trying to add an options popup to the row shortcode (Custom CSS Class, Background Color etc.).

I added the options.php to the main directory, but the options don't appear. Where do I have to include the file, or what do I have to do to add options?

Thanks in advance!

**Comment by moldcraft** [comment]
main directory?

----

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/row/options.php
```

**Comment by tzimpel** [comment]
Exactly that directory.

Content:

`<?php if (!defined('FW')) die('Forbidden');

$options = array(
	'cssclass' => array(
		'type'  => 'text',
		'label' => __( 'Custom CSS Class', 'fw' ),
	),
);`

**Comment by moldcraft** [comment]
Ops, there is no `row` shortcode, there is `column` shortcode

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php
```

**Comment by moldcraft** [comment]
Also there is `section` shortcode

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/options.php
```
