### ISSUE TITLE
Column options not available

### ISSUE THREAD

**Issue by abadrahman** [ThemeFuse/Unyson-Shortcodes-Extension#36]
Hi,

I am looking at the documentation at http://docs.themefuse.com/exposure/your-theme/shortcodes/columns but I cannot seem to find the edit button for the column options.

From looking at the the scratch theme it seems possible to get the edit button and options if you add columns into "framework-customizations/extensions/shortcodes/shortcodes/".

**Comment by moldcraft** [comment]
Hello,

You can create

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php
```

add there some `$options` and the edit button should appear.

An [example in Scratch Theme](https://github.com/ThemeFuse/Scratch-Theme/blob/03e9e2afc0e6fa8bbb0039f321016d9b5ad15db8/scratch-parent/framework-customizations/extensions/shortcodes/shortcodes/column/options.php).
