### ISSUE TITLE
Need a way to enqueue scripts and styles conditionally 

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Shortcodes-Extension#37]
We have an `$atts` variable available in `view.php`, it is very convenient and nice to have it this way.

As a sugestion, it would be nice if `$atts` variable would be available in the `static.php` file as well. That's because I don't want to load some assets in case the user would not need it. 

How complicated this change is? Can I help?

**Comment by moldcraft** [comment]
Sending by defaylt decoded `$atts` in `static.php` will double the decode execution: One decode happens on post content render (the shortcodes are decoded by wordpress) and second decode (for same shortcodes) will happen on `static.php` inclusion.

So better to use [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head) and decode the attributes only for specific/needed shortcodes.
