### ISSUE TITLE
Shortcode with rewrite

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Shortcodes-Extension#38]
We're trying to create a shortcode named `map`. There exists already a shortcode with this name in unyson. Everything works fine besides the fact that when we're trying to access shortcode instance from outside via `fw()->extensions->get('shortcodes')->get_shortcode('map');` it gives us a instance of the class that is in unyson. I am pretty sure that [naming conventions](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#class-file) are respected.

I guess it's a problem with [`rewrite_paths`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2a51926f4ccf549f253df2b0726a422019581fa7/includes/class-fw-shortcodes-loader.php#L214), but not sure.

**Comment by moldcraft** [comment]
You can't overwrite a shortcode, you can only customize it (`static.php`, `options.php`, etc.)

**Comment by andreiglingeanu** [comment]
You cannot customize the class for the shortcode?

**Comment by moldcraft** [comment]
Unfortunately, nope.
