### ISSUE TITLE
Can't render shortcode when you don't have global $post

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Shortcodes-Extension#39]
I'm trying to create a wordpress ajax action that will give me html for a specific shortcode. When I try to render the shortcode I'm getting `Shortcode attributes decode error: Global $post is required.` error that comes from [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/class-fw-shortcode.php#L162). That's because you're not having the `global $post` when you're in ajax action.

```php
function ct_handle_get_shortcode_html () {
	$shortcode_name = $_POST['shortcode_name'];
	$options = $_POST['options'];

	echo fw()->extensions->get('shortcodes')->get_shortcode('button')->render(
		$options
	);

	die();
}
```

I would like to be able to pass an argument to the `render()` method that will skip `$atts` decoding step, I'll give it a valid set of options. 

```php
echo fw()->extensions->get('shortcodes')->get_shortcode('button')->render(
	$options,
	null,
	'',
	array('skip_decoding' => true)
);
```

I can implement it by myself and come up with a pull request.

What do you think?

**Comment by andreiglingeanu** [comment]
@moldcraft One more issue with `skip_decoding` option.

I've got this option in one of my shortcodes (pay attention to the name with a hyphen (box**-**title):
```
'box-title' => array(
	'attr'  => array( 'class' => 'heading_advanced_styling' ),
	'label' => __( 'Title', 'fw' ),
	'desc'  => __( 'Enter the icon box title', 'fw' ),
	'type'  => 'text',
),
```

When normally rendering shortcode I'm not skipping decoding phase and decoder transforms `box-title` into `box_title`. I also have noticed that this behavior is not consistent (sorry, I've not checked out decoder code), sometimes I get version with a hyphen in my view.php.

When I'm adding `skip_decoding` option to the `render()`, `$atts` from the `view.php` are not transformed at all. It gives me the version from the `options.php`.

I don't want to maintain two versions of my `view.php`. Is there a way to add consistency into this behavior? Maybe I can come up with a pull request if you'll give me some insights into this.

**Comment by moldcraft** [comment]
I haven't tested your pull request (with skipping).

I'll inspect this issue.

**Comment by andreiglingeanu** [comment]
@moldcraft Thanks.

**Comment by andreiglingeanu** [comment]
@moldcraft This is not fixed.

When I'm rendering shortcode as usual I'm getting `box_title`. When rendering manually, from wp_ajax action I have `box-title`. 
<hr>
[Here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/helpers.php#L16) I'm getting [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/class-fw-extension-shortcodes.php#L205) coders: [debug session](https://www.dropbox.com/s/12vnu2awv4a4hg8/Screenshot%202015-11-30%2015.11.30.png?dl=0)

So we have two coders: `json` and `post_meta` to check for `can_decode()` [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/helpers.php#L17). In my next [debug session](https://www.dropbox.com/s/t4oz0i5kn15d6k0/Screenshot%202015-11-30%2015.18.07.png?dl=0) you can see that no one of them can decode this `$attributes`, that's why they remain [intact](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/helpers.php#L22).

**Comment by andreiglingeanu** [comment]
When I'm forcing to use `json` decoder to work using this trick:
```
$options['_made_with_builder'] = true;
```

I'm getting error `PHP Warning:  html_entity_decode() expects parameter 1 to be string, array given` right [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/coder/class-fw-ext-shortcodes-attr-coder-json.php#L87).

**Comment by moldcraft** [comment]
> When I'm rendering shortcode as usual I'm getting box_title. When rendering manually, from wp_ajax action I have box-title.

Why don't you just rename that option to `box_title` ?

**Comment by andreiglingeanu** [comment]
I have a lot of shortcodes with a lot of options, It's not a best practice to rename every such option in this way..

**Comment by andreiglingeanu** [comment]
@moldcraft Maybe it's a problem with [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/coder/class-fw-ext-shortcodes-attr-coder-json.php#L24)?

**Comment by andreiglingeanu** [comment]
@moldcraft I've created a duplicate for options  in my code this way:

```php
foreach ($options as $key => $value) {
	$key = str_replace('-', '_', $key);

	$options[$key] = $value;
}
```

And it worked.

**Comment by moldcraft** [comment]
https://codex.wordpress.org/Shortcode_API#Attributes

![](https://static.md/335842d078435ce7f97901815336d778.png)

I can remove the code that does the `-` to `_` replace, but I am afraid that some themes may have options with `-` but in view are working with `_`. For example they saw that it is replaced, but haven't reported that (as you did) and continued to develop the theme.

If I will remove the replace, in their views will come atts with `-` (instead of expected `_`), and the frontend will contain notices/errors.
