### ISSUE TITLE
Customize Section, Column Item types

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Shortcodes-Extension#41]
Can I get [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/40#issuecomment-160135453) functional for those item types also? 

I guess child shortcodes for this ones are stored inside `this.model.collection`, right?

I can come up myself with a pull request for this, just let me know if you don't have the time to deal with this. Thanks.

**Comment by moldcraft** [comment]
> child shortcodes for this ones are stored inside `this.model.collection`

Yes

> I can come up myself with a pull request for this, just let me know if you don't have the time to deal with this.

Do please, I am busy with https://github.com/ThemeFuse/Unyson/issues/838

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/42
