### ISSUE TITLE
I'm using it but received the error below.

### ISSUE THREAD

**Issue by neliocastro** [ThemeFuse/Unyson-Shortcodes-Extension#43]
Fatal error: Only variables can be passed by reference in /home/storage/d/ef/8c/faculdadebaianadedir/public_html/portal/wp-content/plugins/u-shortcodes/shortcodes/monthview/month.php on line 2

Check it on: http://www.faculdadebaianadedireito.com.br/portal/graduacao/#m-12-2015

Thanks
Nélio

**Comment by moldcraft** [comment]
Hello, please address this question to theme/plugin author (the error is not from unyson)
