### ISSUE TITLE
Is There Any method that could be able to show map in frontend?

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Unyson-Shortcodes-Extension#44]
When I use custom meta in post type, I found that I could use map option type. So, is there any method that could be able to show map in the frontend. Or, is that possible to use map shortcode in frontend php code. Is there any documentation for that? Or Could you show me a example code for that? Thanks in advance.

**Comment by moldcraft** [comment]
Hello,

All options values are saved in database depending on where they are placed (post options, theme settings options, etc.) http://manual.unyson.io/en/latest/helpers/php.html#database

Option types works only in backend, in frontend you get only database value and do whatever you want with it.

**Comment by moldcraft** [comment]
Shortcode options values are available in shortcode view file as `$atts` variable http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-shortcode-with-options

**Comment by hlaporthein** [comment]
Thanks @moldcraft , I understand what you mean. What I would like to know.... is.... page builder section has already included shortcodes for map. So, when I use map option type in custom meta fields, I have to set up map box with custom meta fields options again. In fact, that would be great if I could be able to reuse map shortcode functions that has already included in page builder. So, I don't need to create the map again for custom meta value for frontend. Anyway, Thanks for your answer.
