### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson-Shortcodes-Extension#46]
> https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/45

Hi,

Couldn't post it on the main wall but I'm looking for developing of this kind of image shortcode: http://prntscr.com/9uhps0

1.Upload one picture and then adjust to upload a picture in the small zoomed/focused picture. Maybe there is more than me that would request this.
1. Another thing would be a nice skill bar or skill counter.
2. Last thing would be to have a possible to link all headers elements to a specifik url. And also possible to link in the content element like paragraph. Its Possible in "write-html" but the main reason for this plugin is to do it easier to non php developers. So I'm just asking.

Thanks in advanced.

**Comment by alriksson** [comment]
Thanks moldcraft.

Also ask if there would be able to build in the function of go from a color to a darker when over a bottom?
So in setting I could choose two color I would like one original color and one when hoover. Just now it's just available to pick one color and then when over it's make the bottom lighter. Couldn't find anything in php  just add a new color.

Is it possible to add?

thanks.

**Comment by danyj** [comment]
Bud , you be much better off by just photoshoping  the image with the action 
http://webdesignandsuch.com/4-free-magnifying-glass-loupe-photoshop-psd-files-for-layouts/

instead of coding this and messing with upload , move , reupload , adjust color etc
