### ISSUE TITLE
How to override map short-code

### ISSUE THREAD

**Issue by sulmanpucit** [ThemeFuse/Unyson-Shortcodes-Extension#54]
I see we have following

fw_ext('shortcodes')->get_shortcode('map');

Can you please tell me how to modify this code so that child framework file is loaded?

Thanks in advance :)

**Comment by moldcraft** [comment]
You can't overwrite `class-fw-shortcode-map.php`.

Disable the `map` shortcode and [create](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content) `your_map` shortcode (a copy of `map`).

**Comment by sulmanpucit** [comment]
Okay, thanks :)
