### ISSUE TITLE
'class-fw-shortcode-team-member.php' not working

### ISSUE THREAD

**Issue by jonmlas** [ThemeFuse/Unyson-Shortcodes-Extension#56]
I want to overwrite the team-member shortcode with my own. Everything works well except that when I add the file "class-fw-shortcode-team-member.php" that enables me to select the views of my shortcode just like the demo-three in the scratch theme, it doesn't work. What it does is use the plugin's view.php and just ignores my custom code.

The original team-member shortcode doesn't have a class-fw-shortcode-team-member.php file. I've properly setup the class-fw-shortcode-team-member.php file and class FW_Shortcode_Team_Member but it still doesn't work.

It will only work if I delete the team-member shortcode folder from the plugin or rename my shortcode(but it would be like creating a new shortcode)

Is the class-fw-shortcode-{your-shortcode-folder-name}.php only for original shortcodes? Not for overrides?

**Comment by moldcraft** [comment]
> Is the class-fw-shortcode-{your-shortcode-folder-name}.php only for original shortcodes? Not for overrides?

Yes.

Better disable the original team-member shortcode, copy it as your own shortcode (with prefixed name) and do whatever you want there.
