### ISSUE TITLE
Thinking about a better way of doing dynamic CSS for shortcodes

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Shortcodes-Extension#62]
First, I would like to know what techniques do you really use?

The most simple one is of course using `style` attribute, like this:

```php
<p style="color: <?php echo esc_attr($atts['color']) ?>;" >Hello, World!</p>
```
I would simply skip this idea because it is obvious and HTML looks very ugly.

<hr>

Next one, as described [here](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head): You have to hook onto an action and then call `wp_add_inline_style` function. The problem with this is that you are committing yourself to one specific css file because of the way `wp_add_inline_style` works.

While doing [WP-Shortcodes](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension), I've noticed a big problem with this. The dynamic styles for each of the shortcode you're inserting into post editor (or any `wp-editor`) won't be included.

The thing we adhered to is that `wp-editor` won't include Unyson button by default. That's because you'll have to do apply `do_shortcode` function to the result you're receiving from `wp-editor`. And also call a helper that we'll implement later that will include all the dynamic CSS.

The problem is that this will introduce two problems:

1. Theme developers will have a little more work while integrating `wp-editor`
2. You'll have one more `<style>` tag besides each included shortcode

The second one is most annoying.

Shortcodes from post editor can be handled a bit more easily -- without developer's implication.

<hr>

Let me know what you think about all of this.

**Comment by moldcraft** [comment]
> Shortcodes from post editor can be handled a bit more easily -- without developer's implication.

How they do the enqueue of css and dynamic css?

**Comment by llemurya** [comment]
maybe with CSSOM https://github.com/israelidanny/veinjs

**Comment by moldcraft** [comment]
It's almost the same as inline css

> @andreiglingeanu I would simply skip this idea because it is obvious and HTML looks very ugly.

**Comment by andreiglingeanu** [comment]
@moldcraft Not quite. There can be LOTS of css and the flexibility is going down very fast.

@llemurya It is better to add it from backend. Doing this operation from JS in the frontend at a regular basis can:

1. slow down frontend
2. Double the CSS on the page (you'll have to add it somewhere in every shortcode, smth like `data-fw-shortcode-dynamic-css`).
3. Introduce flickers (the phase when the CSS will not be yet loaded). That's very annoying.

**Comment by danyj** [comment]
I am using the head embed , no inlines at all because as you said they are very ugly and  unorganized , 

> The problem with this is that you are committing yourself to one specific css file because of the way wp_add_inline_style works.

I dont see problem in there because you have min one styleshet in your theme so why not use that , 

I went one step further and created a CSS collect class that I am using in each shortcode 

    ThzDochead::getDocument()->addCssInhead( $add_css );

where add_css  is the var that holds the dinamic css for the shorcode

than I call the  wp_add_inline_style only once in the hooks 




	/**
	 * Dynamic CSS
	 */
	function _thz_action_enqueue_dynamic_scripts() {
		
		
		// theme settings collection
		$add_css = _thz_site_dynamic_css();
		
		// Google fonts collection
		if ( isset( ThzDochead::getDocument()->dochead['googlefont'] ) && !empty( ThzDochead::getDocument()->dochead['googlefont'] ) ) {        
			
			$all_google_fonts = implode( '|', array_unique( ThzDochead::getDocument()->dochead['googlefont'] ) );
			$google_font_url  = add_query_arg( 'family', urlencode( $all_google_fonts ), "//fonts.googleapis.com/css" );
			wp_enqueue_style( THEME_NAME . '-google-font', esc_url( $google_font_url ), false, null, 'all' );
		}
		
		// cssinhead shortcodes collection
		if ( isset( ThzDochead::getDocument()->dochead['cssinhead'] ) ) {
			$add_css .= implode( ThzDochead::getDocument()->dochead['cssinhead'] );
		}
	
	
		// custom CSS , last
		$add_css .= thz_print_codes('custom_css');
		
		wp_add_inline_style( THEME_NAME . '-template', $add_css );
	
	
	}
	
	add_action( 'wp_enqueue_scripts', '_thz_action_enqueue_dynamic_scripts', 90 );


this way I ednup with nice and clean embed , that I can also compress to a file etc.
http://prntscr.com/bph1or

which changes depending on where you are and if the shortcode is used or not

**Comment by andreiglingeanu** [comment]
> I dont see problem in there because you have min one styleshet in your theme so why not use that ,
Sometimes when you are loading it TOO _early_, the theme css is not yet loaded, for some reason. We need a bulletproof one that will be around 100%. That's what I'm looking for now.

**Comment by danyj** [comment]
@andreiglingeanu  well ,  WP never introduced  something like this 
https://docs.joomla.org/J3.x:Adding_JavaScript_and_CSS_to_the_page
https://api.joomla.org/cms-3/classes/JDocument.html


which would be perfect for your issue and everyone else so we are stuck on wp_add_inline_style  or the ugly inlines.

**Comment by andreiglingeanu** [comment]
Okay, I figured it out how it works.

The good news are that you can insert _any_ shortcode directly in the post editor, and [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.16/class-fw-extension-shortcodes.php#L118) will handle it accordingly. The bad ones consist of the fact that you can't just insert them anywhere else without much work.

I'll try to categorise all the use cases below and the work you have to do for each of them.

|use case\what you get | HTML | assets from `static.php` | dynamic css|
|------|----------|---------------------------------|-----------------|
| 1. Shortcode In Post Editor  | 👍    | 👍  | 👍   |
| 2. Shortcode in `wp-editor` of any Page-Builder Shortcode | 👍   | 👍  | ❌   |
| 3. Shortcode in `wp-editor` of that is inserted anywhere else (like Theme Settings or any `fw.OptionsModal`) | 👍   | ❌  | ❌   |

_Notes:_
In category **1.** and **2.** you'll have to do `echo do_shortcode($wp_editor_content);` in order to get HTML.

The parts with ❌  you're supposed to handle by yourself.

<hr>

To conclude, there's no way of getting an universal solution for all of this. That's it, we tried and we failed.
Let me know if you think about something better.

**Comment by danyj** [comment]
@andreiglingeanu ,  can you provide the snippets for  2 and 3  that we can use please.

**Comment by andreiglingeanu** [comment]
@danyj Will do.

**Comment by andreiglingeanu** [comment]
Upd. Because of [this](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/master/class-fw-extension-wp-shortcodes.php#L119) now shortcodes within other PB Shortcodes are handled correctly (use case 2). Table below also update.

[Detailed documentation to come.](http://manual.unyson.io/en/latest/extension/wp-shortcodes/index.html)

**Comment by danyj** [comment]
@andreiglingeanu    about the static and dynamic anywhere ,  


this is my notification shortcode static 

http://prntscr.com/bv9z4v

isnt there any way for you to add a hook or custom term to the post once the shortcode is inserted via editor so that I could do something like this 


    add_action('fw_shortcode_notification_active','_thz_notification_css');

I mean , I can make that function available in my  helpers.php and call it where ever you give the hook, it does not have to be bound to static.php  since I use same coding pattern in every shortcode.

**Comment by andreiglingeanu** [comment]
@danyj Do you mean dealing about 3rd use case?

**Comment by danyj** [comment]
> Do you mean dealing about 3rd use case?

yes, if at all possible, il bend over and backwards since I am not done and that feature would mean alot.

**Comment by andreiglingeanu** [comment]
Let's say you have an editor in TS and you can get it's result like this:

```php
$content = fw_get_db_settings_option('editor');

// add this HTML somewhere in your templates, like this
echo do_shortcode($content);
```

Now you're done with first phase - `HTML`, two more to get done.
Now let's deal with statics:

```php
add_action( 'wp_enqueue_scripts', '_handle_my_editor_statics' );

function _handle_my_editor_statics () {
  // get same content once again
  $content = fw_get_db_settings_option('editor');

  // then use it to load all of the statics for your shortcodes
  // both `static.php` and dynamic ones
  fw_ext_shortcodes_enqueue_shortcodes_static(
    $content
  );
}
```

**Comment by danyj** [comment]
ok than that is the solution :+1:  , why are you marking it as no possible?

**Comment by danyj** [comment]
should rather mar as manual instead "no"  here

![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/16991871/5bc078e2-4e9d-11e6-88f5-e5925125a0a8.jpg)

**Comment by andreiglingeanu** [comment]
Yeah, I really meant that you have to do some more work in order to get this done correctly.

**Comment by danyj** [comment]
I'm sure none of us mind the work when something like this is in question. we waited to long the the "Holy Andrei" :))))

**Comment by andreiglingeanu** [comment]
@danyj Yeah) Let me know how it goes, especially if it goes wrong.

**Comment by thednp** [comment]
I think super sharp about this, here we go: why use inline CSS, head CSS, whatever dynamic CSS when you can have 2-3 classes as option choices we can simply setup in a shortcode options, or simply a `text` option type to add comma/space separated classes and have ALL CSS IN ONE FILE.

For me, except `video` and `maps` shortcodes, I disabled all shortcodes statics, I don't need them, I have all CSS done for LTR, RTL, IE_Legacy, etc, why add even more CSS (inline/head/separate file).

I would like to have a single thing to do this stuff: 
* **raw HTML editor shortcode**
* dynamic or whatever you call it, or what user really needs... CSS/JS
* make it work with Wordpress natively, whatever
* no changes to the current shortcodes existing as of now
* if user wants to go the hard way, let him have his freedom, but don't open pandora's box for a little fuzz.

I don't know what you get from it, I haven't slept in the last 30+ hours.

**Comment by danyj** [comment]
@andreiglingeanu , just tested the custom dynamic CSS addon  https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/62#issuecomment-233979434

and works like charm!  THANK YOU!!!!

**Comment by andreiglingeanu** [comment]
@danyj Great news, I've also tested it a lot and looks like it works fine. It may also appear some small flaws, and I am aware of that. Just keep me in sync with all of this.

**Comment by tlartaud** [comment]
Hi there, hi @andreiglingeanu 
Is it possible to add the WP Shortcodes button on a non-tinyMCE WP Editor on the frontend ? I use Summernote on my theme on frontend which is a standard textarea switched on domReady to an advanced text editor using jQuery. Any way to have shortcodes working on a textarea on the frontend ? Is it limited to tinyMCE ? Should the shortcodes button work on a tinyMCE wp-editor displayed on the frontend ?

Regards.

**Comment by andreiglingeanu** [comment]
> on the frontend
Not impossible. We just need the right guy to come up with a pull request for that. I won't even try to do this for now.

> standard textarea switched on domReady to an advanced text editor using jQuery
That's also possible. You'll just have to think about some other way to visualise your shortcodes in textarea -- your business.

> Is it limited to tinyMCE
It is working only on tinyMCE for now. But there's nothing stopping you from implementing the UI in some different way. Good luck.

**Comment by dmbostan** [comment]
Guys, 
wouldn't it be easier to generate a css file on save_post / theme options save?

I mean I use the page builder mostly and do a lot of changes to sections, columns, etc.

Why not create dynamic css files on save? One for section, another for columns, based on how many shortcodes are used on a specific page. And display that specific CSS files for that specific page?

Or ...

add extra option to options 

```array(
    'type'  => 'color-picker',
    'value' => '#FF0000',
   ...
    'in_css' => array('background-color')
)```

Let's parse each option and read the value and in_css. And based on this generate a dynamic css file.

Just ideas :)
