### ISSUE TITLE
When I clone a shortcode the input are empty

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Shortcodes-Extension#63]
When I clone a shortcode (with this shrtcode generator) the input are empty
https://static.md/9bacb6219b65aa9069f0acb81c4969f3.png

**Comment by andreiglingeanu** [comment]
@andronic90 What's the expected behavior? You have some defaults set in your `value`?

Maybe you can provide a step by step reproduction steps?

**Comment by andronic90** [comment]
Yes, I will discuss this problem with moldcraft on monday. Is simple:
Step 1: Add a text block shortcode with this generator (unyson icon).
Step 2: Complete some values for examplte "lorem ipsum"
Step 3. Clone this shortcode (and the values of the cloned shortcode are empty, or come with a default values for example button shortcode)

**Comment by andreiglingeanu** [comment]
Ah. Got it. I'll come up with a fix.

**Comment by andreiglingeanu** [comment]
e4a2b3d5e1b0e798a9216f3bccd374a27ba83dcf

**Comment by andronic90** [comment]
Ok, thanks. I will test this on monday
