### ISSUE TITLE
.gitignore prevents a good release

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson-Shortcodes-Extension#74]
Hello, 

when releasing a project for e.g. on PRODuction, the .gitignore in this repo will prevent the extensions folder from being released.

Not sure if it's your issue though.

**Comment by toleabivol** [comment]
Forgot to mention that the release is done via git offcourse (that's why it is an issue)

**Comment by toleabivol** [comment]
But even if i remove this .gitignore and add all files the extension appears in available (not active - though db is synced) and when i click activate it shows an error .

![unyson manitese wordpress](https://cloud.githubusercontent.com/assets/3755796/24405211/ba47f3be-13cc-11e7-96b5-82c989e0ccc2.jpeg)

**Comment by toleabivol** [comment]
With debug true it displays :
`Cannot activate hidden standalone extension Shortcodes`

**Comment by toleabivol** [comment]
Ah , sorry , please ignore the last 2 comments/error. It was from my debugging of the issue.

But the issue with .gitignore still remains.

**Comment by GheorgheP** [comment]
Ok, but `.gitignore` ignores the `extensions` folder content from the it's core, not from your theme folder.
But if you are editing the original extension `extensions` folder, that you should not do, then this is up to you.

More then that, the sub-extensions capability was not a good idea, and we dot not recommend using this possibility, better create the extensions as first level extension, but with dependence to the `shortcodes` extension.

**Comment by toleabivol** [comment]
Yes , a meant the `extensions` folder from `plugins/unyson/` . So on local I have this folder that will not be committed because of the .gitignore in this extension and thus not released to PROD :
`wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder`

**Comment by GheorgheP** [comment]
Sure, because the sub-extensions are not part of Shortcodes extension, as the Page Builder extension is in another repository. You have to extend your script in order o commit the sub-extensions also.

Same thing as the `extensions` folder in Unyson plugin, it ignores all the content inside except `update` and `blog` extensions.

**Comment by toleabivol** [comment]
I see , ok it's a release thing so not your issue totally.
