### ISSUE TITLE
https://trello.com/c/MSzv6SkU/22-reporting-unyson-bugs

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Shortcodes-Extension#8]
Hello everyone,

I have a problem in using text block from page builder. Text block is giving me extra <br> tag after the paragraph. I am testing with unyson plugin and scratch parent theme(latest versions).

I could be able to remove that extra <br/> tag using regular expression and wpauto function. But, when I view unyson plugin live site, there is not extra <br/> tag in text block. What am I missing?

Do I need to edit anything (content filter) in plugin to remove <br/> tag?

Here is my screenshot problem link https://www.dropbox.com/s/mvgtl3jjtzohrf3/screenshot.png?dl=0

**Comment by scurrilus** [comment]
Hi, i thing this is a problem produced by the wp-editor. If you change wp-content/plugins/unyson/extensions/shortcodes/text-block/options.php 'type'  => 'wp-editor' to 'type'  => 'text', everyfing works fine. But this is not the best solution.

I don't know what how to fix the reason but we can fix the aftereffects. This litte hack wait untit the page is load, find the <br> and remove it from page.

1. create a File content/plugins/unyson/extensions/shortcodes/text-block/static.php

```php
<?php if (!defined('FW')) die('Forbidden');

$shortcodes_extension = fw_ext('shortcodes');
wp_enqueue_script(
	'fw-shortcode-text-block',
	$shortcodes_extension->get_declared_URI('/shortcodes/text-block/static/js/text-block-hack.js')
);
```

2. create a File content/plugins/unyson/extensions/shortcodes/text-block/static/js/text-block-hack.js

```javascript

(function ($) {
	$( document ).ready(function() {
		$(".unyson-text-block p").next('br').remove();
		console.log( "ready!" );
	});
	
})(jQuery);
```

3. Ad <div> container with class class='unyson-text-block' in file content/plugins/unyson/extensions/shortcodes/text-block/view/view.php

```php
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
} ?>

<?php echo "<div class='unyson-text-block'>" . do_shortcode($atts['text']) . "</div>" ;?>
```

**Comment by scurrilus** [comment]
Hi @GheorgheP thank you for the update it works very well. Note: to take effect all text-block elements must be re-added. Nevertheless, there is still a problem. When use of ul list there is still a br after each li element. Do you have any idea? Thanks alot. I like this Plugin.

```html
<ul><br>
<li>test</li><br>
<li>test</li><br>
<li>test</li><br>
</ul>
```
