### ISSUE TITLE
Events Manager and text-block issue

### ISSUE THREAD

**Issue by ddzieduch** [ThemeFuse/Unyson-Shortcodes-Extension#80]
I have problem with /events/ page - [Events Manager](https://wordpress.org/plugins/events-manager/)
Page that list all created events.

I want put some description before and after events table with two columns and text block.

And i get 
`Undefined index: text in /wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/text-block/views/view.php on line 9`

Is it possible that these two plugins work together?

Unyson 2.7.10
Events Manager 5.8.1.1

**Comment by ViorelEremia** [comment]
I see in page events "This page corresponds to the Events Manager Events page. Its content will be overridden by Events Manager, although if you include the word CONTENTS (exactly in capitals) and surround it with other text, only CONTENTS will be overwritten." admin notice added by Events Manager plugin so you can't. You can use shortcodes inside tinymce editor around the word CONTENTS.
