### ISSUE TITLE
Documentation: stored post content

### ISSUE THREAD

**Issue by colinduwe** [ThemeFuse/Unyson-Shortcodes-Extension#81]
We're using the Jevelin theme. If I build a page with 'sections' it is stored in the json stored in postmeta but not in the content field of post in the posts table.

How do I control what is stored in the content field vs. the json postmeta?

**Comment by ViorelEremia** [comment]
If I understand you correctly you're looking for this function: https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/class-fw-extension-page-builder.php#L174
We created this function for seo plugins to store some data into post content. 
You can control it via the hook save_post but why? What do you want to do?

**Comment by colinduwe** [comment]
Thanks. I will read. My issue has to do with the Jevelin theme which implements a custom version of the section shortcode with options for a parallax bg image, video, etc. If you set the parallax option it writes un-enclosed js to the content so calling the_excerpt() returns "jQuery({...." which messes up search results. Shufflehound has been unhelpful in fixing this so I'm trying to figure it out.

**Comment by ViorelEremia** [comment]
You can see here:https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/class-fw-extension-page-builder.php#L213 we delete all tags leave only <a><p><h1><h2><h3><h4><h5><h6><img> 
I tested with some themes and scratch themes and unyson dosen't touch excerpt and for content stripping tags is working

**Comment by colinduwe** [comment]
@ViorelEremia Thanks so much for pointing me in the right direction. I've submitted a PR over in the appropriate project
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/pull/107
