### ISSUE TITLE
Add an input for map zoom

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Shortcodes-Extension#9]
I have 2 maps on contact form and and other page, and the map zoom is different.
I use Shortcode map.

**Comment by GheorgheP** [comment]
By default the map shortcode doesn't have the zoom option, the map zoom depends on the markers position. 

You can set new option in map options and name it zoom:
```php
'map_zoom' => array(
	'label' => __( 'Map Zoom', 'fw' ),
	'desc'  => __( 'Set map zoom level', 'fw' ),
	'type'  => 'slider',
	'properties' => array(
		'min' => 1,
		'max' => 16,
	)
),
```

Then in `map/static/js/scripts.js`, under line 10 add this code:
```js
var zoom = parseInt( $mapWrapper.data('map-zoom') ) > 0 ? parseInt( $mapWrapper.data('map-zoom') ) : 4;
```

Under line 18 add this code:
```js
zoom : zoom,
```

Andon line 77 replace this code:
```js
map.fitBounds(markerBounds);
```
with this code:
```js
if (locations.length > 1) {
	map.fitBounds(markerBounds);
}
```
